version: "3"
services:
  hugo:
    image: klakegg/hugo:0.82.0-ext
    user: 1000:1000
    command:
      - "-s /src -d /public -e production"
    volumes:
      - "./src:/src"
      - "./public:/public"

  # localhost:1313
  server:
    image: klakegg/hugo:0.82.0-ext
    command:
      - server
    user: 1000:1000
    environment:
      - HUGO_PARAMS_ENV=local
    volumes:
      - "./src:/src"
    ports:
      - 1313:1313
