# Failed to persist entry: API_ERROR: Although you appear to have the correct authorization credentials, the `betagouv` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
backend:
  name: github
  repo: betagouv/preuve-covoiturage-vitrine
  branch: main
  base_url: https://ghoauth.osc-fr1.scalingo.io/

media_folder: src/static/images
public_folder: images

locale: fr

slug:
  clean_accents: true

collections:
  - label: "📄 Pages"
    name: pages
    files:
      - label: "🏡 Accueil"
        name: home
        file: src/data/home.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: "Compétences : titre"
            name: expertise_title
            widget: string
          - label: Compétences
            name: expertise_list
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Image
                name: image
                widget: image
          - label: "Documentation : titre"
            name: doc_title
            widget: string
          - label: "Documentation : description"
            name: doc_description
            widget: markdown
          - label: "Documentation : image"
            name: doc_image
            widget: image
          - label: "Documentation : titre du lien"
            name: doc_link_title
            widget: string
          - label: "Documentation : lien"
            name: doc_link_href
            widget: string
          - label: "Outils : titre"
            name: tools_title
            widget: string
          - label: Outils
            name: tools
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Description
                name: description
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: "Titre du lien"
                name: link_title
                widget: string
              - label: Lien
                name: link_href
                widget: string

      - label: "👥 Qui sommes-nous ?"
        name: qui-sommes-nous
        file: src/content/qui-sommes-nous/_index.md
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: Contenu
            name: body
            widget: markdown

      - label: "🚘 Opérateurs"
        name: operateurs
        file: src/content/operateurs/_index.md
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: "Titre des opérateurs liés"
            name: section_linked_title
            widget: string
          - label: "Titre des opérateurs non liés"
            name: section_notlinked_title
            widget: string

      - label: "🏛️ Territoires"
        name: territoires
        file: src/content/territoires/_index.md
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: Contenu
            name: body
            widget: markdown

  - label: "📝 Blocks"
    name: blocks
    files:
      - label: "🙋 Vous êtes..."
        name: vousetes
        file: src/data/vousetes.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Cartes
            label_singular: carte
            name: cards
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Bouton
                name: link_title
                widget: string
              - label: Lien
                name: link_href
                widget: string

      - label: "😉 Témoignages"
        name: testimonials
        label_singular: Témoignage
        file: src/data/testimonials.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Témoignages
            label_singular: Témoignage
            name: cards
            widget: list
            fields:
              - label: Aute·ur·rice
                name: title
                widget: string
              - label: Témoignage
                name: description
                widget: text

      - label: "📈 Statistiques"
        name: stats
        label_singular: Statistique
        file: src/data/stats.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Statistiques
            label_singular: Statistique
            name: cards
            widget: list
            fields:
              - label: Description
                name: description
                widget: markdown
              - label: "Visible sur la page d'accueil"
                name: pinned
                widget: boolean
                default: false
              - label: Image
                name: image
                widget: image
                required: false
              - label: Titre du lien
                name: link_title
                widget: string
                required: false
              - label: Lien
                name: link_href
                widget: string
                required: false

  - name: operateurs
    label: "🚘 Opérateurs"
    label_singular: Opérateur
    folder: src/content/operateurs
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    filter:
      field: filter
      value: operateur
    fields:
      - label: Nom
        name: title
        widget: string
      - label: Publication
        name: date
        widget: datetime
        date_format: "DD/MM/YYYY"
        time_format: "HH:mm"
        picker_utc: false
      - label: "Connecté au RPC"
        name: linked
        widget: boolean
        default: false
      - label: Logo
        name: logo
        widget: image
        required: false
        allow_multiple: false
        media_folder: /src/static/images/operateurs
        public_folder: /images/operateurs
      - label: "Site web"
        name: link
        widget: string
        required: false

  - name: territoires
    label: "🏛️ Territoires"
    label_singular: Territoire
    folder: src/content/territoires
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    filter:
      field: filter
      value: territoire
    fields:
      - label: Nom
        name: title
        widget: string
      - label: Publication
        name: date
        widget: datetime
        date_format: "DD/MM/YYYY"
        time_format: "HH:mm"
        picker_utc: false
      - label: "Afficher le nom"
        name: showTitle
        widget: boolean
        default: true
      - label: Logo
        name: logo
        widget: image
        required: false
        allow_multiple: false
        media_folder: /src/static/images/operateurs
        public_folder: /images/operateurs

  - name: settings
    label: "⚙️ Paramètres"
    files:
      - label: "Services"
        name: services
        file: src/data/services.yml
        editor:
          preview: false
        fields:
          - { label: Application, name: app, widget: string }
          - { label: API, name: api, widget: string }
          - { label: Statistiques, name: stats, widget: string }
          - { label: "Mentions légales", name: legal, widget: string }
          - { label: "Ministère de la transition écologique", name: ministry, widget: string }
          - { label: Doc, name: doc, widget: string }
          - { label: Doc technique, name: tech, widget: string }
          - { label: Attestations, name: cert, widget: string }
          - { label: Statut, name: status, widget: string }
          - { label: "Code source", name: sourcecode, widget: string }
          - { label: "beta.gouv", name: betagouv, widget: string }
      - label: "Réseaux sociaux"
        name: social
        file: src/data/social.yml
        editor:
          preview: false
        fields:
          - { label: Twitter, name: twitter, widget: string }
          - { label: Youtube, name: api, widget: string }
          - { label: LinkedIn, name: linkedin, widget: string }
          - { label: Github, name: github, widget: string }
          - { label: RSS, name: rss, widget: string }
      - label: "Newsletter"
        name: newsletter
        file: src/data/newsletter.yml
        editor:
          preview: false
        fields:
          - { label: Activée, name: enabled, widget: boolean, default: false }
          - { label: "Form action (URL)", name: action, widget: string }
      - label: "Formulaire de contact"
        name: contactform
        file: src/data/contactform.yml
        editor:
          preview: false
        fields:
          - { label: "Form action (URL)", name: action, widget: string }
      - label: "Matomo"
        name: analytics
        file: src/data/analytics.yml
        editor:
          preview: false
        fields:
          - { label: "id", name: id, widget: string }
